import { MakeLogicType, actions, connect, kea, listeners, path, reducers } from 'kea'
import { loaders } from 'kea-loaders'

import { i18n } from 'lib/i18n/i18n'
import { lemonToast } from 'lib/lemon-ui/LemonToast/LemonToast'
import { teamLogic } from 'scenes/teamLogic'

import { insightsBulkSetTestAccountFilterCreate } from 'products/product_analytics/frontend/generated/api'
import { InsightBulkSetTestAccountFilterResponseApi } from 'products/product_analytics/frontend/generated/api.schemas'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface applyTestAccountFilterLogicValues {
    currentProjectId: number | string // teamLogic
    bulkSetResponse: InsightBulkSetTestAccountFilterResponseApi | null
    bulkSetResponseLoading: boolean
    pendingEnabled: boolean | null
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface applyTestAccountFilterLogicActions {
    applyToExistingInsights: (enabled: boolean) => {
        enabled: boolean
    }
    applyToExistingInsightsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    applyToExistingInsightsSuccess: (
        bulkSetResponse: InsightBulkSetTestAccountFilterResponseApi,
        payload?: {
            enabled: boolean
        }
    ) => {
        bulkSetResponse: InsightBulkSetTestAccountFilterResponseApi
        payload?: {
            enabled: boolean
        }
    }
}

export type applyTestAccountFilterLogicType = MakeLogicType<
    applyTestAccountFilterLogicValues,
    applyTestAccountFilterLogicActions
>

export const applyTestAccountFilterLogic = kea<applyTestAccountFilterLogicType>([
    path(['scenes', 'settings', 'environment', 'applyTestAccountFilterLogic']),
    connect(() => ({
        values: [teamLogic, ['currentProjectId']],
    })),
    actions({
        applyToExistingInsights: (enabled: boolean) => ({ enabled }),
    }),
    reducers({
        pendingEnabled: [
            null as boolean | null,
            {
                applyToExistingInsights: (_, { enabled }) => enabled,
                applyToExistingInsightsSuccess: () => null,
                applyToExistingInsightsFailure: () => null,
            },
        ],
    }),
    loaders(({ values }) => ({
        bulkSetResponse: [
            null as InsightBulkSetTestAccountFilterResponseApi | null,
            {
                applyToExistingInsights: async ({ enabled }: { enabled: boolean }) => {
                    return await insightsBulkSetTestAccountFilterCreate((values.currentProjectId ?? '').toString(), {
                        enabled,
                    })
                },
            },
        ],
    })),
    listeners(() => ({
        applyToExistingInsightsSuccess: ({ bulkSetResponse, payload }) => {
            if (!bulkSetResponse) {
                return
            }
            const { updated, unsupported, skipped, legacy } = bulkSetResponse
            const extras = [
                unsupported > 0
                    ? i18n.t('settings.environment.testAccountFilters.existingInsights.extraUnsupported', {
                          count: unsupported,
                          defaultValue_one: '{{ count }} with no such filter, like SQL insights',
                          defaultValue_other: '{{ count }} with no such filter, like SQL insights',
                      })
                    : null,
                // The two with a next step say what it is. Nothing can put the toggle on a SQL insight.
                skipped > 0
                    ? i18n.t('settings.environment.testAccountFilters.existingInsights.extraSkipped', {
                          count: skipped,
                          defaultValue_one: "{{ count }} you can't edit (an organization admin can apply it to those)",
                          defaultValue_other:
                              "{{ count }} you can't edit (an organization admin can apply it to those)",
                      })
                    : null,
                legacy > 0
                    ? i18n.t('settings.environment.testAccountFilters.existingInsights.extraLegacy', {
                          count: legacy,
                          defaultValue_one: '{{ count }} saved in an older format (open and save one to convert it)',
                          defaultValue_other: '{{ count }} saved in an older format (open and save one to convert it)',
                      })
                    : null,
            ].filter(Boolean)
            const leftAlone =
                extras.length > 0
                    ? i18n.t('settings.environment.testAccountFilters.existingInsights.leftAlone', {
                          extras: extras.join(', '),
                          defaultValue: ' Left alone: {{ extras }}.',
                      })
                    : ''
            if (updated > 0) {
                lemonToast.success(
                    (payload?.enabled
                        ? i18n.t('settings.environment.testAccountFilters.existingInsights.appliedOn', {
                              count: updated,
                              defaultValue_one: 'Turned the filter on for {{ count }} insight',
                              defaultValue_other: 'Turned the filter on for {{ count }} insights',
                          })
                        : i18n.t('settings.environment.testAccountFilters.existingInsights.appliedOff', {
                              count: updated,
                              defaultValue_one: 'Turned the filter off for {{ count }} insight',
                              defaultValue_other: 'Turned the filter off for {{ count }} insights',
                          })) + `.${leftAlone}`
                )
            } else {
                // "Needed changing" would be a lie when insights were held back rather than already correct.
                const nothing =
                    extras.length > 0
                        ? i18n.t('settings.environment.testAccountFilters.existingInsights.nothingChanged', {
                              defaultValue: 'No insights changed.',
                          })
                        : i18n.t('settings.environment.testAccountFilters.existingInsights.nothingNeededChanging', {
                              defaultValue: 'No insights needed changing.',
                          })
                lemonToast.info(`${nothing}${leftAlone}`)
            }
        },
        applyToExistingInsightsFailure: () => {
            lemonToast.error(
                i18n.t('settings.environment.testAccountFilters.existingInsights.applyFailed', {
                    defaultValue: 'Could not update your existing insights. Try again in a moment.',
                })
            )
        },
    })),
])
