import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers, selectors } from 'kea'
import { loaders } from 'kea-loaders'

import api from 'lib/api'
import { i18n } from 'lib/i18n/i18n'
import { lemonToast } from 'lib/lemon-ui/LemonToast/LemonToast'
import { teamLogic } from 'scenes/teamLogic'

import { CoreEvent } from '~/queries/schema/schema-general'

/** API response type for core events */
interface CoreEventResponse {
    id: string
    name: string
    description: string
    category: string
    filter: Record<string, unknown>
    created_at: string
    updated_at: string
}

/** Convert API response to CoreEvent type */
function toCoreEvent(response: CoreEventResponse): CoreEvent {
    return {
        id: response.id,
        name: response.name,
        description: response.description,
        category: response.category as CoreEvent['category'],
        filter: response.filter as unknown as CoreEvent['filter'],
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface coreEventsLogicValues {
    currentTeamId: number | null // teamLogic
    coreEvents: CoreEvent[]
    coreEventsLoader: any
    coreEventsLoaderLoading: boolean
    coreEventsLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface coreEventsLogicActions {
    addCoreEvent: (event: Omit<CoreEvent, 'id'>) => {
        event: Omit<CoreEvent, 'id'>
    }
    loadCoreEvents: () => any
    loadCoreEventsFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadCoreEventsSuccess: (
        coreEventsLoader: any,
        payload?: any
    ) => {
        coreEventsLoader: any
        payload?: any
    }
    removeCoreEvent: (eventId: string) => {
        eventId: string
    }
    setCoreEvents: (events: CoreEvent[]) => {
        events: CoreEvent[]
    }
    updateCoreEvent: (event: CoreEvent) => {
        event: CoreEvent
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface coreEventsLogicMeta {
    __keaTypeGenInternalSelectorTypes: {
        coreEventsLoading: (coreEventsLoaderLoading: boolean) => boolean
    }
}

export type coreEventsLogicType = MakeLogicType<
    coreEventsLogicValues,
    coreEventsLogicActions,
    Record<string, any>,
    coreEventsLogicMeta
>

export const coreEventsLogic = kea<coreEventsLogicType>([
    path(['scenes', 'settings', 'environment', 'coreEventsLogic']),
    connect(() => ({
        values: [teamLogic, ['currentTeamId']],
    })),
    actions({
        setCoreEvents: (events: CoreEvent[]) => ({ events }),
        addCoreEvent: (event: Omit<CoreEvent, 'id'>) => ({ event }),
        updateCoreEvent: (event: CoreEvent) => ({ event }),
        removeCoreEvent: (eventId: string) => ({ eventId }),
    }),
    reducers({
        coreEvents: [
            [] as CoreEvent[],
            {
                setCoreEvents: (_, { events }) => events,
            },
        ],
    }),
    loaders(({ values, actions }) => ({
        coreEventsLoader: {
            loadCoreEvents: async () => {
                if (!values.currentTeamId) {
                    return []
                }
                try {
                    const response = await api.get(`api/environments/${values.currentTeamId}/core_events/`)
                    const events = (response.results || []).map(toCoreEvent)
                    actions.setCoreEvents(events)
                    return events
                } catch {
                    return []
                }
            },
        },
    })),
    selectors({
        coreEventsLoading: [(s) => [s.coreEventsLoaderLoading], (loading: boolean) => loading],
    }),
    listeners(({ values, actions }) => ({
        addCoreEvent: async ({ event }) => {
            if (!values.currentTeamId) {
                return
            }
            try {
                await api.create(`api/environments/${values.currentTeamId}/core_events/`, event)
                actions.loadCoreEvents()
                lemonToast.success(
                    i18n.t('settings.environment.coreEvents.toasts.added', { defaultValue: 'Core event added' })
                )
            } catch {
                lemonToast.error(
                    i18n.t('settings.environment.coreEvents.toasts.addFailed', {
                        defaultValue: 'Failed to add core event',
                    })
                )
            }
        },
        updateCoreEvent: async ({ event }) => {
            if (!values.currentTeamId) {
                return
            }
            try {
                await api.update(`api/environments/${values.currentTeamId}/core_events/${event.id}/`, event)
                actions.loadCoreEvents()
                lemonToast.success(
                    i18n.t('settings.environment.coreEvents.toasts.updated', { defaultValue: 'Core event updated' })
                )
            } catch {
                lemonToast.error(
                    i18n.t('settings.environment.coreEvents.toasts.updateFailed', {
                        defaultValue: 'Failed to update core event',
                    })
                )
            }
        },
        removeCoreEvent: async ({ eventId }) => {
            if (!values.currentTeamId) {
                return
            }
            try {
                await api.delete(`api/environments/${values.currentTeamId}/core_events/${eventId}/`)
                actions.loadCoreEvents()
                lemonToast.success(
                    i18n.t('settings.environment.coreEvents.toasts.removed', { defaultValue: 'Core event removed' })
                )
            } catch {
                lemonToast.error(
                    i18n.t('settings.environment.coreEvents.toasts.removeFailed', {
                        defaultValue: 'Failed to remove core event',
                    })
                )
            }
        },
    })),
    afterMount(({ actions }) => {
        actions.loadCoreEvents()
    }),
])
