import { MakeLogicType, actions, afterMount, connect, kea, listeners, path, reducers } from 'kea'
import { loaders } from 'kea-loaders'

import api from 'lib/api'
import { i18n } from 'lib/i18n/i18n'
import { lemonToast } from 'lib/lemon-ui/LemonToast/LemonToast'
import { teamLogic } from 'scenes/teamLogic'
import { userLogic } from 'scenes/userLogic'

import { ApprovalPolicy, AvailableFeature } from '~/types'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface approvalPoliciesLogicValues {
    hasAvailableFeature: (feature: AvailableFeature, currentUsage?: number | undefined) => boolean // userLogic
    policies: ApprovalPolicy[]
    policiesLoading: boolean
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface approvalPoliciesLogicActions {
    createPolicy: (policy: Partial<ApprovalPolicy>) => {
        policy: Partial<ApprovalPolicy>
    }
    deletePolicy: (id: string) => {
        id: string
    }
    loadPolicies: () => {
        value: true
    }
    loadPoliciesFailure: (
        error: string,
        errorObject?: any
    ) => {
        error: string
        errorObject?: any
    }
    loadPoliciesSuccess: (
        policies: ApprovalPolicy[],
        payload?: {
            value: true
        }
    ) => {
        policies: ApprovalPolicy[]
        payload?: {
            value: true
        }
    }
    updatePolicy: (
        id: string,
        policy: Partial<ApprovalPolicy>
    ) => {
        id: string
        policy: Partial<ApprovalPolicy>
    }
}

export type approvalPoliciesLogicType = MakeLogicType<approvalPoliciesLogicValues, approvalPoliciesLogicActions>

export const approvalPoliciesLogic = kea<approvalPoliciesLogicType>([
    path(['scenes', 'settings', 'organization', 'Approvals', 'approvalPoliciesLogic']),
    connect(() => ({
        values: [userLogic, ['hasAvailableFeature']],
    })),
    actions({
        loadPolicies: true,
        createPolicy: (policy: Partial<ApprovalPolicy>) => ({ policy }),
        updatePolicy: (id: string, policy: Partial<ApprovalPolicy>) => ({ id, policy }),
        deletePolicy: (id: string) => ({ id }),
    }),
    loaders(({ values }) => ({
        policies: [
            [] as ApprovalPolicy[],
            {
                loadPolicies: async () => {
                    const teamId = teamLogic.values.currentTeamId
                    if (!teamId || !values.hasAvailableFeature(AvailableFeature.APPROVALS)) {
                        return []
                    }
                    const response = await api.get<{ results: ApprovalPolicy[] }>(
                        `api/environments/${teamId}/approval_policies/`
                    )
                    return response.results || []
                },
            },
        ],
    })),
    reducers({
        policies: {
            updatePolicy: (state, { id, policy }) =>
                state.map((p) => (p.id === id ? { ...p, ...policy } : p)) as ApprovalPolicy[],
            deletePolicy: (state, { id }) => state.filter((p) => p.id !== id),
        },
    }),
    listeners(({ actions }) => ({
        createPolicy: async ({ policy }) => {
            try {
                const teamId = teamLogic.values.currentTeamId
                if (!teamId) {
                    throw new Error(
                        i18n.t('settings.organization.approvals.noTeam', { defaultValue: 'No team selected' })
                    )
                }
                await api.create(`api/environments/${teamId}/approval_policies/`, policy)
                lemonToast.success(
                    i18n.t('settings.organization.approvals.created', { defaultValue: 'Approval policy created' })
                )
                actions.loadPolicies()
            } catch (error: any) {
                lemonToast.error(
                    error.detail ||
                        i18n.t('settings.organization.approvals.createFailed', {
                            defaultValue: 'Failed to create approval policy',
                        })
                )
            }
        },
        updatePolicy: async ({ id, policy }) => {
            try {
                const teamId = teamLogic.values.currentTeamId
                if (!teamId) {
                    throw new Error(
                        i18n.t('settings.organization.approvals.noTeam', { defaultValue: 'No team selected' })
                    )
                }
                await api.update(`api/environments/${teamId}/approval_policies/${id}/`, policy)
                lemonToast.success(
                    i18n.t('settings.organization.approvals.updated', { defaultValue: 'Approval policy updated' })
                )
                actions.loadPolicies()
            } catch (error: any) {
                lemonToast.error(
                    error.detail ||
                        i18n.t('settings.organization.approvals.updateFailed', {
                            defaultValue: 'Failed to update approval policy',
                        })
                )
            }
        },
        deletePolicy: async ({ id }) => {
            try {
                const teamId = teamLogic.values.currentTeamId
                if (!teamId) {
                    throw new Error(
                        i18n.t('settings.organization.approvals.noTeam', { defaultValue: 'No team selected' })
                    )
                }
                await api.delete(`api/environments/${teamId}/approval_policies/${id}/`)
                lemonToast.success(
                    i18n.t('settings.organization.approvals.deleted', { defaultValue: 'Approval policy deleted' })
                )
                actions.loadPolicies()
            } catch (error: any) {
                lemonToast.error(
                    error.detail ||
                        i18n.t('settings.organization.approvals.deleteFailed', {
                            defaultValue: 'Failed to delete approval policy',
                        })
                )
            }
        },
    })),
    afterMount(({ actions }) => {
        actions.loadPolicies()
    }),
])
