// Generated by frontend/bin/build-i18n-catalogs.mjs. Do not edit by hand.

import type { CatalogLoader } from './catalogs'
import type { TranslationNamespace } from './namespaces'
import type { LocaleCode } from './supportedLocales'

/**
 * One import per catalog. Each entry is a static import path so that a bundler emits a
 * separate chunk for it, and the loader map is what turns a language choice into a download.
 *
 * The source locale keeps no loader: its messages are the English text at each call site.
 */
export const CATALOG_LOADERS: Record<LocaleCode, Partial<Record<TranslationNamespace, CatalogLoader>>> = {
    en: {},
    'zh-CN': {
        common: () => import('./locales/zh-CN/common.json'),
    },
    'zh-TW': {
        common: () => import('./locales/zh-TW/common.json'),
    },
    'ja-JP': {
        common: () => import('./locales/ja-JP/common.json'),
    },
    'ko-KR': {
        common: () => import('./locales/ko-KR/common.json'),
    },
    'de-DE': {
        common: () => import('./locales/de-DE/common.json'),
    },
    'fr-FR': {
        common: () => import('./locales/fr-FR/common.json'),
    },
    'es-ES': {
        common: () => import('./locales/es-ES/common.json'),
    },
    'pt-BR': {
        common: () => import('./locales/pt-BR/common.json'),
    },
    'ru-RU': {
        common: () => import('./locales/ru-RU/common.json'),
    },
}
